name: Trigger auto deployment for fastapi-on-azure-functions

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fastapi-on-azure-functions-AutoDeployTrigger-61445182-eaff-4575-a28b-861045715b17.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FASTAPIONAZUREFUNCTIONS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASTAPIONAZUREFUNCTIONS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASTAPIONAZUREFUNCTIONS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: crc7r4wgfdetiym.azurecr.io
          registryUsername: ${{ secrets.FASTAPIONAZUREFUNCTIONS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASTAPIONAZUREFUNCTIONS_REGISTRY_PASSWORD }}
          containerAppName: fastapi-on-azure-functions
          resourceGroup: rg-off-ice
          imageToBuild: crc7r4wgfdetiym.azurecr.io/fastapi-on-azure-functions:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


